### ISSUE TITLE
All incoming calls shows as private numbers

### ISSUE THREAD

**Issue by fractal1510** [DeadSquirrel01/sailfishos-a5ultexx-releases#2]
If a call is missed, there is no way to call back since it was registered as private, not sure how to debug this since the OS is new to me, systemd-journald service is masked and if i unmask it, the OS can no longer boot. Also the Sailfish OS cheat sheet says that for calling diagnostics some changes to the source code should be made.

**Comment by Ansfer** [comment]
Hello! Can you make sailfishos support for the A500F?
lineage-14.1-20181114-UNOFFICIAL-a5ultexx.zip is not stitched in TWRP writes error 7

**Comment by DeadSquirrel01** [comment]
fixed with https://github.com/DeadSquirrel01/ofono/commit/75180373c5f9da7a515a9db4808eb8b7f1322005 (ofono>=1.64 or release>=20190609)
