### ISSUE TITLE
a500h didnt see sim card

### ISSUE THREAD

**Issue by kekxd** [DeadSquirrel01/sailfishos-a5ultexx-releases#3]
have a500h (dual sim)
if flash los rom, flash sfos rom, flash ril fix - sfos didnt see sim card. 
if i flash only los rom - same issue. 
if i flash los + fix ril - it works. 
i try to flash in this order: 1)los 2)sfos 3)ril and 1)los 2)ril 3)sfos - any result.
please help me, tnx!

**Comment by edp17** [comment]
You reported it work when you do los + fix ril. Have you tried to flash sfos on top of that? Like: 1) los, 2) ril, 3) sfos ?

**Comment by kekxd** [comment]
not actually, sir.  i sold that mobile 2 years ago
